//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDrink
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int IdHoadon { get; set; }
        public Nullable<int> IdNuoc { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<int> IdNhanvien { get; set; }
        public Nullable<double> Thanhtien { get; set; }
    
        public virtual NuocUong NuocUong { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
