//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDrink
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public int IdTK { get; set; }
        public string Taikhoan { get; set; }
        public string Matkhau { get; set; }
        public string Chucvu { get; set; }
    }
}
